const std = @import("std");

const V8_VERSION: []const u8 = "14.0.365.4";

const LazyPath = std.Build.LazyPath;

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    var build_opts = b.addOptions();
    build_opts.addOption(
        bool,
        "inspector_subtype",
        b.option(bool, "inspector_subtype", "Export default valueSubtype and descriptionForValueSubtype") orelse true,
    );

    const prebuilt_v8_path = b.option([]const u8, "prebuilt_v8_path", "Path to prebuilt libc_v8.a");

    const prepared_v8 = try prepareV8Sources(b);
    const bootstrapped_v8 = bootstrapV8(b, prepared_v8);

    const built_v8 = if (prebuilt_v8_path) |path| blk: {
        // Use prebuilt_v8 if available.
        const wf = b.addWriteFiles();
        _ = wf.addCopyFile(b.path(path), "libc_v8.a");
        break :blk wf;
    } else blk: {
        // Otherwise, go through build process.
        break :blk try buildV8(b, prepared_v8, bootstrapped_v8, target, optimize);
    };

    const prepare_step = b.step("prepare-v8", "Prepare V8 source code");
    prepare_step.dependOn(&prepared_v8.step);
    prepare_step.dependOn(&bootstrapped_v8.step);

    const build_step = b.step("build-v8", "Build v8");
    build_step.dependOn(&built_v8.step);

    // the module we export as a library
    const v8_module = b.addModule("v8", .{
        .root_source_file = b.path("src/v8.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
        .link_libcpp = true,
    });
    v8_module.addIncludePath(b.path("src"));
    v8_module.addImport("default_exports", build_opts.createModule());
    v8_module.addObjectFile(built_v8.getDirectory().path(b, "libc_v8.a"));

    switch (target.result.os.tag) {
        .macos => {
            v8_module.addSystemFrameworkPath(.{ .cwd_relative = "/System/Library/Frameworks" });
            v8_module.linkFramework("CoreFoundation", .{});
        },
        else => {},
    }

    {
        const test_module = b.createModule(.{
            .root_source_file = b.path("src/v8.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
            .link_libcpp = true,
        });

        // test
        const tests = b.addTest(.{
            .root_module = test_module,
        });
        tests.root_module.addImport("default_exports", build_opts.createModule());

        const release_dir = if (optimize == .Debug) "debug" else "release";
        const os = switch (target.result.os.tag) {
            .linux => "linux",
            .macos => "macos",
            .ios => "ios",
            else => return error.UnsupportedPlatform,
        };

        tests.addObjectFile(b.path(b.fmt("v8/out/{s}/{s}/obj/zig/libc_v8.a", .{ os, release_dir })));
        tests.addIncludePath(b.path("src"));

        switch (target.result.os.tag) {
            .macos => {
                // v8 has a dependency, abseil-cpp, which, on Mac, uses CoreFoundation
                tests.addSystemFrameworkPath(.{ .cwd_relative = "/System/Library/Frameworks" });
                tests.linkFramework("CoreFoundation");
            },
            else => {},
        }

        const run_tests = b.addRunArtifact(tests);
        const tests_step = b.step("test", "Run unit tests");
        tests_step.dependOn(&run_tests.step);
    }
}

fn prepareV8Sources(b: *std.Build) !*std.Build.Step.WriteFile {
    const wf = b.addWriteFiles();

    // Create .gclient file for gclient
    const gclient_content = b.fmt(
        \\solutions = [
        \\  {{
        \\    "name": ".",
        \\    "url": "https://chromium.googlesource.com/v8/v8.git@{s}",
        \\    "deps_file": "DEPS",
        \\    "managed": False,
        \\    "custom_deps": {{}},
        \\  }},
        \\]
        \\
    , .{V8_VERSION});
    _ = wf.add(".gclient", gclient_content);

    // Copy binding files
    _ = wf.addCopyFile(b.path("src/binding.cpp"), "binding.cpp");
    _ = wf.addCopyFile(b.path("src/inspector.h"), "inspector.h");
    // Copy build configuration
    _ = wf.addCopyFile(b.path("build-tools/BUILD.gn"), "zig/BUILD.gn");
    // Not sure if it's a Zig bug or intended behavior but, addCopyFile won't
    // overwrite the original .gn. This means we put it in here and just call it from there.
    _ = wf.addCopyFile(b.path("build-tools/.gn"), "zig/.gn");
    // Generate gclient_args.gni
    _ = wf.add("build/config/gclient_args.gni",
        \\# Generated by Zig build system
        \\
    );
    return wf;
}

fn bootstrapV8(b: *std.Build, prepared_v8: *std.Build.Step.WriteFile) *std.Build.Step.Run {
    const depot_tools = b.dependency("depot_tools", .{});

    // Sync dependencies for this version
    var gclient_sync = std.Build.Step.Run.create(b, "run gclient sync");
    gclient_sync.addFileArg(depot_tools.path("gclient"));
    gclient_sync.addArgs(&.{"sync"});
    gclient_sync.setEnvironmentVariable("DEPOT_TOOLS_UPDATE", "0");
    gclient_sync.setCwd(prepared_v8.getDirectory());
    gclient_sync.step.dependOn(&prepared_v8.step);

    // Run clang update script after copying
    const clang_update = b.addSystemCommand(&.{
        "python3",
        "tools/clang/scripts/update.py",
    });
    clang_update.setCwd(prepared_v8.getDirectory());
    clang_update.step.dependOn(&gclient_sync.step);
    return clang_update;
}

fn buildV8(
    b: *std.Build,
    prepared_v8: *std.Build.Step.WriteFile,
    bootstrapped_v8: *std.Build.Step.Run,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !*std.Build.Step.WriteFile {
    const depot_tools = b.dependency("depot_tools", .{});
    const v8_dir = prepared_v8.getDirectory();

    const allocator = b.allocator;

    const tag = target.result.os.tag;
    const arch = target.result.cpu.arch;
    const is_debug = optimize == .Debug;

    var gn_args: std.ArrayList(u8) = .empty;
    defer gn_args.deinit(allocator);

    // official builds depend on pgo
    try gn_args.appendSlice(allocator, "is_official_build=false\n");

    if (is_debug) {
        try gn_args.appendSlice(allocator, "is_debug=true\n");
        try gn_args.appendSlice(allocator, "symbol_level=1\n");
    } else {
        try gn_args.appendSlice(allocator, "is_debug=false\n");
        try gn_args.appendSlice(allocator, "symbol_level=0\n");
    }

    switch (tag) {
        .ios => {
            try gn_args.appendSlice(allocator, "v8_enable_pointer_compression=false\n");
            try gn_args.appendSlice(allocator, "v8_enable_webassembly=false\n");
            // TODO: target_environment for this target.
        },
        .linux => {
            if (arch == .aarch64) {
                try gn_args.appendSlice(allocator, "clang_base_path=\"usr/lib/llvm-21\"\n");
                try gn_args.appendSlice(allocator, "clang_use_chrome_plugins=false\n");
                try gn_args.appendSlice(allocator, "treat_warnings_as_errors=false\n");
            }
        },
        else => {},
    }

    var gn_run = std.Build.Step.Run.create(b, "run gn");
    gn_run.addFileArg(depot_tools.path("gn"));
    gn_run.addArgs(&.{
        "--root=.",
        "--root-target=//zig",
        "--dotfile=zig/.gn",
        "gen",
        "out",
        b.fmt("--args={s}", .{gn_args.items}),
    });
    gn_run.setCwd(v8_dir);
    gn_run.step.dependOn(&prepared_v8.step);
    gn_run.step.dependOn(&bootstrapped_v8.step);

    var ninja_run = std.Build.Step.Run.create(b, "run ninja");
    ninja_run.addFileArg(depot_tools.path("ninja"));
    ninja_run.addArgs(&.{ "-C", "out", "c_v8" });
    ninja_run.setCwd(v8_dir);
    ninja_run.step.dependOn(&gn_run.step);

    const wf = b.addWriteFiles();
    wf.step.dependOn(&ninja_run.step);
    _ = wf.addCopyFile(v8_dir.path(b, "out/obj/zig/libc_v8.a"), "libc_v8.a");

    return wf;
}
