#!/usr/bin/env bash
set -o errexit #  exit on errors
set -o nounset # exit on use of uninitialized variable
set -o errtrace # inherits trap on ERR in function and subshell

source utils.sh

REVISION=14.0.365.4


clone() {
  if [ -d "${2}" ]; then
    warn "dependency ${2} already exists, skipping"
  else
    say "cloning dependency ${1}"
    git  clone --depth=1 "${1}" "${2}"
    pushd "${2}"
      git fetch --depth=1 origin $3
      git -c advice.detachedHead=false checkout $3
      git branch -D \@{-1} || true  # if you want to tidy up the fetched branch
    popd
  fi
}

cloneDep() {
  dep_info=$(python3 deps_get.py deps.json "${1}")
  IFS=@ read -r dep_path dep_commit <<< "${dep_info}"
  clone $dep_path $2 $dep_commit
}

if [ -d "src" ]; then
  warn "v8/src/ already exists, only cloning dependencies"
else
  say "cloning V8 into v8/src/"
  git clone --depth=1 --branch ${REVISION} "https://chromium.googlesource.com/v8/v8.git" src
fi

python3 deps_parse.py src/DEPS > deps.json

cloneDep 'build' 'src/build'
cloneDep 'third_party/jinja2' 'src/third_party/jinja2'
cloneDep 'buildtools' 'src/buildtools'
cloneDep 'tools/clang' 'src/tools/clang'
cloneDep 'third_party/zlib' 'src/third_party/zlib'
cloneDep 'third_party/googletest/src' 'src/third_party/googletest/src'
cloneDep 'third_party/markupsafe' 'src/third_party/markupsafe'
cloneDep 'third_party/icu' 'src/third_party/icu'
cloneDep 'third_party/abseil-cpp' 'src/third_party/abseil-cpp'
cloneDep 'third_party/simdutf' 'src/third_party/simdutf'
cloneDep 'third_party/highway/src' 'src/third_party/highway/src/'
cloneDep 'third_party/libc++/src' 'src/third_party/libc++/src'
cloneDep 'third_party/libc++abi/src' 'src/third_party/libc++abi/src'
cloneDep 'third_party/llvm-libc/src' 'src/third_party/llvm-libc/src'
cloneDep 'third_party/fp16/src' 'src/third_party/fp16/src'
cloneDep 'third_party/fast_float/src' 'src/third_party/fast_float/src'
cloneDep 'third_party/dragonbox/src' 'src/third_party/dragonbox/src'

# Add an empty gclient_args.gni so gn is happy. gclient also creates an empty file.
echo "# generated by get_v8.sh" >  src/build/config/gclient_args.gni

say "gettting prebuilt clang binary"
python3 src/tools/clang/scripts/update.py
